name: Manual
on:
    workflow_dispatch:                          # 수동으로 워크플로우를 실행할 수 있도록 설정
      inputs:                                   # 입력 파라미터명
        greeting:   
            type: string
            default: Hello                      # 입력 파라미터 기본값
            required: true                      # 입력 파라미터 필수 여부
            description: A cheerful word        # 입력값에 대한 설명
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, ${{ github.event.inputs.greeting }}" # 입력받은 greeting 값을 출력